# https://taskfile.dev

version: '3'

vars:
  HostOS:
    sh: go env GOHOSTOS
  HostArch:
    sh: go env GOHOSTARCH

tasks:
  default:
    cmds:
      - task: build
  build:
    cmds:
      - for: [windows, linux, darwin]
        vars:
          Platform: '{{.ITEM}}'
        task: build-for
  build-for:
    internal: true
    vars:
      Platform: '{{.Platform | default .HostOS}}'
      Os: '{{.Platform | replace "darwin" "mac"}}'
    env:
      GOOS: "{{.Platform}}"
    cmds:
      - go build -ldflags="-s -w" -trimpath=1 -o ./bin/{{.Os}}/ ./cmd/nx
  pkg:
    cmds:
      - for: [windows, linux, darwin]
        vars:  
          Platform: '{{.ITEM}}'
        task: pkg-platform
  pkg-platform:
    internal: true
    dir: bin
    vars:
      Platform: '{{.Platform | default .HostOS}}'
      Os: '{{.Platform | replace "darwin" "mac"}}' 
    cmds:
      - task: zip
        vars:
          Files: '.\{{.Os}}\*'
          Output: '{{.Os}}_{{.HostArch}}.zip'
  zip:
    internal: true
    dir: bin
    cmds:
      - cmd: pwd
      - cmd: 7z a {{.Output}} "{{.Files}}" &>/dev/null